#!/bin/bash
#/home/rschubert1/scratch/software/gwasqc_pipeline/shellscripts/01MissingnessFiltering \
#	-a \
#	-b /home/rschubert1/data/GEU/QC/whole_pop/whole_pop \
#	-o /home/rschubert1/data/GEU/QC/whole_pop/
#/home/rschubert1/scratch/software/gwasqc_pipeline/shellscripts/02RelatednessFiltering \
#	-b /home/rschubert1/data/GEU/QC/whole_pop/missingness_hwe_steps/05filtered_HWE \
#	-o /home/rschubert1/data/GEU/QC/whole_pop/ \
#	--rel .5
/home/rschubert1/scratch/software/gwasqc_pipeline/shellscripts/03MergeHapMap \
	-b /home/rschubert1/data/GEU/QC/whole_pop/relatedness_steps/05without_relateds \
	-o /home/rschubert1/data/GEU/QC/whole_pop/ \
	--hapmap /home/rschubert1/data/HAPMAP3_hg19_c_pos/cpos 
	
