#!/bin/bash
for pop in CEU FIN GBR TSI YRI;
do
	/home/rschubert1/scratch/software/gwasqc_pipeline/shellscripts/01MissingnessFiltering \
		-a \
		-b /home/rschubert1/data/GEU/QC/${pop} \
		-o /home/rschubert1/data/GEU/QC/${pop}/
	/home/rschubert1/scratch/software/gwasqc_pipeline/shellscripts/02RelatednessFiltering \
		-b /home/rschubert1/data/GEU/QC/${pop}/missingness_hwe_steps/05filtered_HWE \
		-o /home/rschubert1/data/GEU/QC/${pop}/ \
		--rel 0.25	
done
